name: SonarQube

on:
  workflow_call:
  
jobs:
  SonarQube:
    runs-on: [self-hosted, linux, x64, backend, ci-tests, texas-dc, docker, small]
    name: Sonarqube Scan
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }}
